import { ProjectFile, ProjectType } from '../types';

export function getTemplateFiles(
  type: ProjectType,
  name: string,
  packageName: string,
  useKotlinDsl: boolean
): { files: ProjectFile[]; activeFileId: string; openFileIds: string[] } {
  const packagePath = packageName.replace(/\./g, '/');

  const baseGradleProperties: ProjectFile = {
    id: `file-gradle-props-${Date.now()}`,
    name: 'gradle.properties',
    path: 'gradle.properties',
    isDirectory: false,
    language: 'properties',
    content: `# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Termux Android SDK build tools AAPT2 override
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/opt/android-sdk/build-tools/36.1.0/aapt2`,
  };

  const baseLocalProperties: ProjectFile = {
    id: `file-local-props-${Date.now()}`,
    name: 'local.properties',
    path: 'local.properties',
    isDirectory: false,
    language: 'properties',
    content: `## This file is automatically generated by Android Code Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
sdk.dir=/data/data/com.termux/files/usr/opt/android-sdk
ndk.dir=/data/data/com.termux/files/usr/opt/android-sdk/ndk/29.0.14206865
cmake.dir=/data/data/com.termux/files/usr/opt/android-sdk/cmake/4.1.2`,
  };

  const gradleWrapperFolder: ProjectFile = {
    id: `folder-gradle-${Date.now()}`,
    name: 'gradle',
    path: 'gradle',
    isDirectory: true,
    children: [
      {
        id: `folder-wrapper-${Date.now()}`,
        name: 'wrapper',
        path: 'gradle/wrapper',
        isDirectory: true,
        children: [
          {
            id: `file-wrapper-props-${Date.now()}`,
            name: 'gradle-wrapper.properties',
            path: 'gradle/wrapper/gradle-wrapper.properties',
            isDirectory: false,
            language: 'properties',
            content: `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.13-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists`,
          },
        ],
      },
    ],
  };

  // 1. JETPACK COMPOSE TEMPLATE
  if (type === 'native_compose') {
    const mainActivityId = `file-compose-main-${Date.now()}`;
    const themeFileId = `file-theme-${Date.now()}`;
    const buildGradleId = `file-build-gradle-${Date.now()}`;

    const files: ProjectFile[] = [
      {
        id: `folder-app-${Date.now()}`,
        name: 'app',
        path: 'app',
        isDirectory: true,
        children: [
          {
            id: `folder-src-${Date.now()}`,
            name: 'src',
            path: 'app/src',
            isDirectory: true,
            children: [
              {
                id: `folder-main-${Date.now()}`,
                name: 'main',
                path: 'app/src/main',
                isDirectory: true,
                children: [
                  {
                    id: `file-manifest-${Date.now()}`,
                    name: 'AndroidManifest.xml',
                    path: 'app/src/main/AndroidManifest.xml',
                    isDirectory: false,
                    language: 'xml',
                    content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${packageName}">
    <application
        android:label="${name}"
        android:theme="@android:style/Theme.Material.NoActionBar">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`,
                  },
                  {
                    id: `folder-kotlin-${Date.now()}`,
                    name: 'kotlin',
                    path: 'app/src/main/kotlin',
                    isDirectory: true,
                    children: [
                      {
                        id: `folder-pkg-${Date.now()}`,
                        name: packagePath,
                        path: `app/src/main/kotlin/${packagePath}`,
                        isDirectory: true,
                        children: [
                          {
                            id: mainActivityId,
                            name: 'MainActivity.kt',
                            path: `app/src/main/kotlin/${packagePath}/MainActivity.kt`,
                            isDirectory: false,
                            language: 'kotlin',
                            content: `package ${packageName}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import ${packageName}.ui.theme.${name}Theme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ${name}Theme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    ComposeMainScreen()
                }
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ComposeMainScreen() {
    var counter by remember { mutableStateOf(0) }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("${name}") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer
                )
            )
        },
        floatingActionButton = {
            FloatingActionButton(onClick = { counter++ }) {
                Text("+")
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .padding(padding)
                .padding(16.dp)
                .fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                elevation = CardDefaults.cardElevation(defaultElevation = 6.dp)
            ) {
                Column(modifier = Modifier.padding(20.dp)) {
                    Text("Compose State Manager", style = MaterialTheme.typography.titleMedium)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Value: \$counter", style = MaterialTheme.typography.headlineLarge)
                    Spacer(modifier = Modifier.height(16.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(onClick = { counter++ }) { Text("Increment") }
                        OutlinedButton(onClick = { counter = 0 }) { Text("Reset") }
                    }
                }
            }
        }
    }
}`,
                          },
                          {
                            id: `folder-ui-theme-${Date.now()}`,
                            name: 'ui/theme',
                            path: `app/src/main/kotlin/${packagePath}/ui/theme`,
                            isDirectory: true,
                            children: [
                              {
                                id: themeFileId,
                                name: 'Theme.kt',
                                path: `app/src/main/kotlin/${packagePath}/ui/theme/Theme.kt`,
                                language: 'kotlin',
                                isDirectory: false,
                                content: `package ${packageName}.ui.theme

import androidx.compose.material3.*
import androidx.compose.runtime.Composable

@Composable
fun ${name}Theme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = darkColorScheme(),
        typography = Typography(),
        content = content
    )
}`,
                              },
                            ],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: buildGradleId,
            name: useKotlinDsl ? 'build.gradle.kts' : 'build.gradle',
            path: useKotlinDsl ? 'app/build.gradle.kts' : 'app/build.gradle',
            isDirectory: false,
            language: 'gradle',
            content: `plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "${packageName}"
    compileSdk = 35

    defaultConfig {
        applicationId = "${packageName}"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"
    }

    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.11"
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom:2024.05.00"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.activity:activity-compose:1.9.0")
}`,
          },
        ],
      },
      gradleWrapperFolder,
      baseGradleProperties,
      baseLocalProperties,
    ];

    return {
      files,
      activeFileId: mainActivityId,
      openFileIds: [mainActivityId, themeFileId, buildGradleId],
    };
  }

  // 2. BOTTOM NAVIGATION TEMPLATE
  if (type === 'bottom_nav') {
    const mainActivityId = `file-botnav-main-${Date.now()}`;
    const xmlLayoutId = `file-botnav-layout-${Date.now()}`;
    const menuXmlId = `file-botnav-menu-${Date.now()}`;

    const files: ProjectFile[] = [
      {
        id: `folder-app-${Date.now()}`,
        name: 'app',
        path: 'app',
        isDirectory: true,
        children: [
          {
            id: `folder-src-${Date.now()}`,
            name: 'src',
            path: 'app/src',
            isDirectory: true,
            children: [
              {
                id: `folder-main-${Date.now()}`,
                name: 'main',
                path: 'app/src/main',
                isDirectory: true,
                children: [
                  {
                    id: `file-manifest-${Date.now()}`,
                    name: 'AndroidManifest.xml',
                    path: 'app/src/main/AndroidManifest.xml',
                    isDirectory: false,
                    language: 'xml',
                    content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="${packageName}">
    <application android:label="${name}" android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar">
        <activity android:name=".BottomNavActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`,
                  },
                  {
                    id: `folder-kotlin-${Date.now()}`,
                    name: 'kotlin',
                    path: 'app/src/main/kotlin',
                    isDirectory: true,
                    children: [
                      {
                        id: `folder-pkg-${Date.now()}`,
                        name: packagePath,
                        path: `app/src/main/kotlin/${packagePath}`,
                        isDirectory: true,
                        children: [
                          {
                            id: mainActivityId,
                            name: 'BottomNavActivity.kt',
                            path: `app/src/main/kotlin/${packagePath}/BottomNavActivity.kt`,
                            isDirectory: false,
                            language: 'kotlin',
                            content: `package ${packageName}

import android.os.Bundle
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.bottomnavigation.BottomNavigationView

class BottomNavActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_bottom_nav)

        val tvStatus = findViewById<TextView>(R.id.tvFragmentStatus)
        val bottomNav = findViewById<BottomNavigationView>(R.id.bottomNavigation)

        bottomNav.setOnItemSelectedListener { item ->
            when (item.itemId) {
                R.id.navigation_home -> {
                    tvStatus.text = "Active Screen: Home Dashboard"
                    true
                }
                R.id.navigation_search -> {
                    tvStatus.text = "Active Screen: Explore & Search"
                    true
                }
                R.id.navigation_notifications -> {
                    tvStatus.text = "Active Screen: Notifications Feed"
                    true
                }
                R.id.navigation_profile -> {
                    tvStatus.text = "Active Screen: User Settings & Account"
                    true
                }
                else -> false
            }
        }
    }
}`,
                          },
                        ],
                      },
                    ],
                  },
                  {
                    id: `folder-res-${Date.now()}`,
                    name: 'res',
                    path: 'app/src/main/res',
                    isDirectory: true,
                    children: [
                      {
                        id: `folder-layout-${Date.now()}`,
                        name: 'layout',
                        path: 'app/src/main/res/layout',
                        isDirectory: true,
                        children: [
                          {
                            id: xmlLayoutId,
                            name: 'activity_bottom_nav.xml',
                            path: 'app/src/main/res/layout/activity_bottom_nav.xml',
                            isDirectory: false,
                            language: 'xml',
                            content: `<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#0F172A">

    <TextView
        android:id="@+id/tvHeader"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="${name} Navigation"
        android:textColor="#38BDF8"
        android:textSize="20sp"
        android:textStyle="bold"
        android:padding="20dp" />

    <TextView
        android:id="@+id/tvFragmentStatus"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="Active Screen: Home Dashboard"
        android:textColor="#F8FAFC"
        android:textSize="16sp" />

    <com.google.android.material.bottomnavigation.BottomNavigationView
        android:id="@+id/bottomNavigation"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:layout_alignParentBottom="true"
        android:background="#1E293B" />

</RelativeLayout>`,
                          },
                        ],
                      },
                      {
                        id: `folder-menu-${Date.now()}`,
                        name: 'menu',
                        path: 'app/src/main/res/menu',
                        isDirectory: true,
                        children: [
                          {
                            id: menuXmlId,
                            name: 'bottom_nav_menu.xml',
                            path: 'app/src/main/res/menu/bottom_nav_menu.xml',
                            isDirectory: false,
                            language: 'xml',
                            content: `<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/navigation_home" android:title="Home" android:icon="@android:drawable/ic_menu_today"/>
    <item android:id="@+id/navigation_search" android:title="Search" android:icon="@android:drawable/ic_menu_search"/>
    <item android:id="@+id/navigation_notifications" android:title="Alerts" android:icon="@android:drawable/ic_popup_reminder"/>
    <item android:id="@+id/navigation_profile" android:title="Profile" android:icon="@android:drawable/ic_menu_myplaces"/>
</menu>`,
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            id: `file-build-gradle-${Date.now()}`,
            name: 'build.gradle',
            path: 'app/build.gradle',
            isDirectory: false,
            language: 'gradle',
            content: `plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace '${packageName}'
    compileSdk 35
    defaultConfig {
        applicationId '${packageName}'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}`,
          },
        ],
      },
      gradleWrapperFolder,
      baseGradleProperties,
      baseLocalProperties,
    ];

    return {
      files,
      activeFileId: xmlLayoutId,
      openFileIds: [xmlLayoutId, mainActivityId, menuXmlId],
    };
  }

  // 3. FLUTTER APPLICATION TEMPLATE
  if (type === 'flutter') {
    const mainDartId = `file-main-dart-${Date.now()}`;
    const pubspecId = `file-pubspec-${Date.now()}`;

    const files: ProjectFile[] = [
      {
        id: `folder-lib-${Date.now()}`,
        name: 'lib',
        path: 'lib',
        isDirectory: true,
        children: [
          {
            id: mainDartId,
            name: 'main.dart',
            path: 'lib/main.dart',
            isDirectory: false,
            language: 'dart',
            content: `import 'package:flutter/material.dart';

void main() => runApp(const ${name}App());

class ${name}App extends StatelessWidget {
  const ${name}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${name}',
      theme: ThemeData.dark(useMaterial3: true),
      home: const CounterScreen(),
    );
  }
}

class CounterScreen extends StatefulWidget {
  const CounterScreen({super.key});

  @override
  State<CounterScreen> createState() => _CounterScreenState();
}

class _CounterScreenState extends State<CounterScreen> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('${name} Flutter Live')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Flutter Mobile IDE Live State:'),
            Text('\$_counter', style: Theme.of(context).textTheme.displayMedium),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => setState(() => _counter++),
        child: const Icon(Icons.add),
      ),
    );
  }
}`,
          },
        ],
      },
      {
        id: pubspecId,
        name: 'pubspec.yaml',
        path: 'pubspec.yaml',
        isDirectory: false,
        language: 'plaintext',
        content: `name: ${name.toLowerCase()}
description: "A professional mobile Flutter project created with Android Code Studio."
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true`,
      },
      baseGradleProperties,
      baseLocalProperties,
    ];

    return {
      files,
      activeFileId: mainDartId,
      openFileIds: [mainDartId, pubspecId],
    };
  }

  // 4. DEFAULT: BASIC ACTIVITY (Kotlin + XML)
  const defaultLayoutId = `file-activity-main-xml-${Date.now()}`;
  const defaultKtId = `file-main-activity-kt-${Date.now()}`;
  const defaultBuildGradleId = `file-app-build-gradle-${Date.now()}`;

  const files: ProjectFile[] = [
    {
      id: `folder-app-${Date.now()}`,
      name: 'app',
      path: 'app',
      isDirectory: true,
      children: [
        {
          id: `folder-src-${Date.now()}`,
          name: 'src',
          path: 'app/src',
          isDirectory: true,
          children: [
            {
              id: `folder-main-${Date.now()}`,
              name: 'main',
              path: 'app/src/main',
              isDirectory: true,
              children: [
                {
                  id: `file-manifest-${Date.now()}`,
                  name: 'AndroidManifest.xml',
                  path: 'app/src/main/AndroidManifest.xml',
                  isDirectory: false,
                  language: 'xml',
                  content: `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${packageName}">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:label="${name}"
        android:theme="@style/Theme.AppCompat.Light.DarkActionBar">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>`,
                },
                {
                  id: `folder-kotlin-${Date.now()}`,
                  name: 'kotlin',
                  path: 'app/src/main/kotlin',
                  isDirectory: true,
                  children: [
                    {
                      id: `folder-pkg-${Date.now()}`,
                      name: packagePath,
                      path: `app/src/main/kotlin/${packagePath}`,
                      isDirectory: true,
                      children: [
                        {
                          id: defaultKtId,
                          name: 'MainActivity.kt',
                          path: `app/src/main/kotlin/${packagePath}/MainActivity.kt`,
                          isDirectory: false,
                          language: 'kotlin',
                          content: `package ${packageName}

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    private var clickCount = 0

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val titleView = findViewById<TextView>(R.id.tvTitle)
        val actionButton = findViewById<Button>(R.id.btnAction)

        actionButton.setOnClickListener {
            clickCount++
            titleView.text = "Clicked $clickCount times!"
            Toast.makeText(this, "Interactive event triggered!", Toast.LENGTH_SHORT).show()
        }
    }
}`,
                        },
                      ],
                    },
                  ],
                },
                {
                  id: `folder-res-${Date.now()}`,
                  name: 'res',
                  path: 'app/src/main/res',
                  isDirectory: true,
                  children: [
                    {
                      id: `folder-layout-${Date.now()}`,
                      name: 'layout',
                      path: 'app/src/main/res/layout',
                      isDirectory: true,
                      children: [
                        {
                          id: defaultLayoutId,
                          name: 'activity_main.xml',
                          path: 'app/src/main/res/layout/activity_main.xml',
                          isDirectory: false,
                          language: 'xml',
                          content: `<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="#0F172A"
    android:padding="20dp">

    <TextView
        android:id="@+id/tvHeader"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="${name}"
        android:textColor="#38BDF8"
        android:textSize="24sp"
        android:textStyle="bold"
        android:layout_marginBottom="8dp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Package: ${packageName}"
        android:textColor="#94A3B8"
        android:textSize="13sp"
        android:layout_marginBottom="24dp" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:background="#1E293B"
        android:padding="16dp"
        android:layout_marginBottom="20dp">

        <TextView
            android:id="@+id/tvTitle"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Ready to build your Android APK"
            android:textColor="#F8FAFC"
            android:textSize="18sp"
            android:textStyle="bold"
            android:layout_marginBottom="12dp" />

        <Button
            android:id="@+id/btnAction"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:text="Tap to Test Interaction"
            android:background="#38BDF8"
            android:textColor="#0F172A"
            android:textStyle="bold" />
    </LinearLayout>

    <EditText
        android:id="@+id/etInput"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:hint="Type user notes here..."
        android:textColor="#FFFFFF"
        android:textColorHint="#64748B"
        android:background="#1E293B"
        android:padding="12dp" />

</LinearLayout>`,
                        },
                      ],
                    },
                    {
                      id: `folder-values-${Date.now()}`,
                      name: 'values',
                      path: 'app/src/main/res/values',
                      isDirectory: true,
                      children: [
                        {
                          id: `file-strings-${Date.now()}`,
                          name: 'strings.xml',
                          path: 'app/src/main/res/values/strings.xml',
                          isDirectory: false,
                          language: 'xml',
                          content: `<resources>\n    <string name="app_name">${name}</string>\n</resources>`,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: defaultBuildGradleId,
          name: useKotlinDsl ? 'build.gradle.kts' : 'build.gradle',
          path: useKotlinDsl ? 'app/build.gradle.kts' : 'app/build.gradle',
          isDirectory: false,
          language: 'gradle',
          content: `plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace '${packageName}'
    compileSdk 35
    defaultConfig {
        applicationId '${packageName}'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}`,
        },
      ],
    },
    gradleWrapperFolder,
    baseGradleProperties,
    baseLocalProperties,
  ];

  return {
    files,
    activeFileId: defaultLayoutId,
    openFileIds: [defaultLayoutId, defaultKtId, defaultBuildGradleId],
  };
}
